FROM python:slim

ENV MPD_FRIENDLY_NAME ""
ENV MPD_HOST ""
ENV MPD_PORT ""

ENV SUBSONIC_PARAMETERS_FILE ""

ENV SUBSONIC_FRIENDLY_NAME ""
ENV SUBSONIC_BASE_URL ""
ENV SUBSONIC_PORT ""
ENV SUBSONIC_USER ""
ENV SUBSONIC_PASSWORD ""
ENV SUBSONIC_CREDENTIALS ""
ENV SUBSONIC_UPMPDCLI_BASE_URL ""
ENV SUBSONIC_UPMPDCLI_PORT ""

ENV MIN_COVERAGE ""
ENV ENOUGH_PLAYBACK_SEC ""
ENV SLEEP_TIME ""
ENV VERBOSE ""

ENV REDACT_CREDENTIALS ""

ENV MAX_SUBSONIC_SERVERS ""
ENV MAX_MPD_INSTANCES ""

ENV MPD_CLIENT_TIMEOUT_SEC ""
ENV ITERATION_DURATION_THRESHOLD_PERCENT ""

ENV PYTHONUNBUFFERED=1

RUN mkdir /code
COPY . /code/
WORKDIR /code
RUN pip install .

VOLUME /config

WORKDIR /code/mpd_subsonic_scrobbler/

ENTRYPOINT [ "python3", "scrobbler.py" ]
